### ISSUE TITLE
OSError: exception: access violation reading 0x00000000F74B8AF0

### ISSUE THREAD

**Issue by kgmuzungu** [armstrap/armstrap-pyvirtualbench#10] opened 2020-01-28 19:45 UTC
It seems my python code gets until incl second line

```
virtualbench = PyVirtualBench('VB8012-30DB550')
print(virtualbench)
ps = virtualbench.acquire_power_supply()
```

at acquire_power_supply() I get following error:

```
<pyvirtualbench.PyVirtualBench object at 0x00000184F9266A30>
Traceback (most recent call last):
  File "C:/Users/glanzer/PycharmProjects/pyVirtualBench/testPSandDMM.py", line 18, in <module>
    ps = virtualbench.acquire_power_supply()
  File "C:\Users\glanzer\PycharmProjects\pyVirtualBench\venv\lib\site-packages\pyvirtualbench.py", line 1938, in acquire_power_supply
    return self.PowerSupply(self, device_name, reset)
  File "C:\Users\glanzer\PycharmProjects\pyVirtualBench\venv\lib\site-packages\pyvirtualbench.py", line 1946, in __init__
    status = self.nilcicapi.niVB_PS_InitializeW(self.library_handle, c_wchar_p(self.device_name), c_bool(reset), byref(self.instrument_handle))
OSError: exception: access violation reading 0x00000000F74B8AF0
```

Any hint or help would be awesome!

**Comment by armstrap** [comment] 2020-01-28 20:31
Duplicate of https://github.com/armstrap/armstrap-pyvirtualbench/issues/2

**Closed as completed by armstrap** 2020-01-28 20:31 UTC
